language: python
sudo: required
dist: xenial

addons:
  chrome: stable

services:
  - xvfb

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
  - wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
        
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/bin/
        
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - python -m pip install pip
  - python -m pip install yagmail 
  - python -m pip install selenium	
  - python -m pip install xlrd
  - python -m pip install unidecode
  - python -m pip install pandas

script:
  - python downloadfromMS2.py
  - python dataConverter.py 
  - python downloadMobilityReport.py 
  - qmake -project
  - qmake Covid_19_console.pro
  - make
  - ./Covid_19_console
  - python transformDataOutput.py  
  - python sendEmail.py  
  
  