language: c++
sudo: required
dist: trusty

install:
  - sudo apt-get install build-essential libgl1-mesa-dev

script:
  - source /opt/qt514/bin/qt511-env.sh
  - qmake Covid_19_console.pro
  - make
  - ./Covid_19_console
  